from langchain_core.tools import tool
from pydantic import BaseModel, Field
from typing import Literal


class ReportRequest(BaseModel):
    title: str = "Vision Analysis Report"
    content: str
    analysis_type: str = "general"
    format: Literal["pdf", "docx", "html", "all"] = "all"
    metadata: dict = Field(default_factory=dict)


@tool
def generate_report(
    title: str,
    content: str,
    analysis_type: str = "general",
    format: Literal["pdf", "docx", "html", "all"] = "all",
) -> str:
    """
    Generate a formatted report from analysis results. Supports PDF, DOCX, and HTML formats.

    Args:
        title: Report title
        content: The analysis text content to include in the report
        analysis_type: Type of analysis (general, dashboard, error, camera)
        format: Output format - 'pdf', 'docx', 'html', or 'all'

    Returns:
        A summary of generated report files with their IDs
    """
    from app.services.report_service import report_service

    result = report_service.generate_all(
        title=title,
        content=content,
        analysis_type=analysis_type,
        metadata={"Generated by": "Vision Assistant Multi-Agent", "Model": "nvidia/nemotron-3-nano-omni"},
    )
    return result
