"""Database package exports."""
from db.lifecycle import get_date_range_inspections, get_today_inspections, init_db
from db.models import (
    AlarmLog,
    CameraConfig,
    DatasetAsset,
    DetectionEvent,
    Employee,
    InspectionLog,
    KPITarget,
    Shift,
    SortingCommandLog,
    TraceLog,
)
from db.repositories import (
    get_detection_summary,
    list_detection_events,
    list_sorting_commands,
    save_detection_event,
    save_sorting_command,
    upsert_camera_config,
)
from db.session import (
    Base,
    IS_POSTGRES,
    SQLALCHEMY_DATABASE_URL,
    SessionLocal,
    engine,
    get_database_info,
    get_db,
)

__all__ = [
    "AlarmLog",
    "Base",
    "CameraConfig",
    "DatasetAsset",
    "DetectionEvent",
    "Employee",
    "IS_POSTGRES",
    "InspectionLog",
    "KPITarget",
    "SQLALCHEMY_DATABASE_URL",
    "SessionLocal",
    "Shift",
    "SortingCommandLog",
    "TraceLog",
    "engine",
    "get_database_info",
    "get_date_range_inspections",
    "get_db",
    "get_detection_summary",
    "get_today_inspections",
    "init_db",
    "list_detection_events",
    "list_sorting_commands",
    "save_detection_event",
    "save_sorting_command",
    "upsert_camera_config",
]
